[package]
name = "vc"
version = "0.1.0"
authors = ["Ozan Akın <ozn.akn@gmail.com>"]
edition = "2018"
build   = "build.rs"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
lalrpop-util = "0.17.2"
regex = "0.2.1"
clap = "2.33.0"
