[package]
name = "vc"
version = "0.1.0"
authors = ["Ozan Akın <ozn.akn@gmail.com>"]
edition = "2018"
build   = "build.rs"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
llvm-sys = "90.0.0"
lalrpop-util = "0.17.2"
clap = "2.33.0"
colored = "1.9.1"